[tool.ruff]
line-length = 80
lint.select = ["ALL"]
lint.ignore = ["D203", "D212"]
exclude = [".venv"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 80
exclude = '(\.git|\.venv)'
